name: "PR"

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Docker meta ci
      id: docker_meta_ci
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: registry.scalecity.io/opensource/bookstack-dev
        tag-sha: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    - name: Build and push Dev
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.docker_meta_ci.outputs.tags }}
        labels: ${{ steps.docker_meta_ci.outputs.labels }}
        cache-from: type=registry,ref=registry.scalecity.io/opensource/bookstack-dev:main
        cache-to: type=inline
        build-args: |
          BOOKSTACK_VERSION=${{ steps.getversion.outputs.version }}
        outputs: type=docker,dest=/tmp/image-bookstack.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: image-bookstack
        path: /tmp/image-bookstack.tar
        if-no-files-found: warn
  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: image-bookstack
        path: /tmp
        if-no-files-found: warn
    - name: Load Docker image
      run: |
        docker load --input /tmp/image-bookstack.tar
        docker image ls -a
    - name: Execute End-to-End Test
      run: make e2e
